from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

# --- Strict Assigner Expression Models ---


class SetLiteral(BaseModel):
    value: str | int | float | bool = Field(description="Direct literal value to assign.")


class SetVar(BaseModel):
    var: str = Field(description="Source state variable key to copy value from.")


class NumericDelta(BaseModel):
    op: Literal["increment", "decrement", "multiply", "divide"] = Field(description="Arithmetic operation.")
    amount: float = Field(description="Amount to adjust.")


class StrictAssignment(BaseModel):
    target_var_key: str = Field(description="Target variable key to write into.")
    assignment: SetVar | SetLiteral | NumericDelta = Field(
        description="Assignment logic: literal value, variable reference, or numeric delta."
    )


# --- Strict Closed-Schema Condition Models ---


class ComparisonCondition(BaseModel):
    var: str = Field(description="Left-hand state variable key to evaluate.")
    op: Literal["equals", "not_equals", "gt", "gte", "lt", "lte", "in"] = Field(description="Comparison operator.")
    literal_value: str | int | float | bool | list[str] | None = Field(
        default=None, description="Literal value to match against (use for static comparisons)."
    )
    compare_var: str | None = Field(
        default=None, description="Right-hand state variable key to compare against (for var-to-var comparisons)."
    )


class ConditionGroup(BaseModel):
    logic: Literal["ALL", "ANY"] = Field(default="ALL", description="Evaluate ALL (AND) or ANY (OR) of the conditions.")
    conditions: list[ComparisonCondition] = Field(
        default_factory=list, description="List of atomic comparison conditions."
    )


class LogicalSwitchBranch(BaseModel):
    label: str = Field(description="Branch identifier label (e.g. 'Yes', 'High_Score', 'default').")
    condition: ConditionGroup | None = Field(
        default=None, description="Condition group to match. Set to null for default/fallback branch."
    )
    target: str = Field(description="Downstream target node ID (or 'end').")


class AgenticSwitchBranch(BaseModel):
    label: str = Field(description="Classification case label (e.g. 'Audience', 'Phone', 'FiftyFifty').")
    target: str = Field(description="Downstream target node ID (or 'end').")


# --- Variable & Agentic Output Models ---


class AgenticOutputVar(BaseModel):
    key: str = Field(description="Output variable name.")
    type: Literal["boolean", "bool", "string", "number", "float", "int", "integer"] = Field(
        description="Variable type."
    )


class UpsertVariable(BaseModel):
    key: str = Field(description="Variable key to create or update.")
    type: Literal["boolean", "bool", "string", "number", "float", "int", "integer"] = Field(
        description="Variable type."
    )
    default_value: Any | None = Field(
        default=None,
        description="Optional default value. Must be explicitly set to null/none if not present.",
    )
    description: str | None = Field(
        default=None,
        description="Optional variable description. Must be explicitly set to null/none if not present.",
    )


# --- Polymorphic Node Configurations ---


class LogicalAssignerConfig(BaseModel):
    assignments: list[StrictAssignment] = Field(min_length=1, description="List of variable assignments to execute.")


class AgenticAssignerConfig(BaseModel):
    prompt: str = Field(description="Prompt template instruction with optional {var} placeholders.")
    agentic_inputs: list[str] = Field(
        default_factory=list, description="Variables passed to the agent context. Pass [] if empty."
    )
    agentic_outputs: list[AgenticOutputVar] = Field(
        default_factory=list, description="Output variables generated by the agent. Pass [] if empty."
    )


class RagRetrieverConfig(BaseModel):
    query_var: str = Field(description="Variable containing the search query string.")
    context_output_var: str = Field(description="Variable to output the retrieved context string.")
    knowledge_base: str = Field(description="Target knowledge base identifier.")
    top_k: int = Field(default=3, description="Number of context records to retrieve.")


class InterruptConfig(BaseModel):
    resume_var: str = Field(description="Variable to write resume value to.")
    payload_vars: list[str] = Field(
        default_factory=list, description="Variables to send in the interrupt payload. Pass [] if empty."
    )


class LogicalSwitchConfig(BaseModel):
    branches: list[LogicalSwitchBranch] = Field(
        default_factory=list, description="List of conditional branches with their condition rules and targets."
    )


class AgenticSwitchConfig(BaseModel):
    agentic_input: str = Field(description="Input variable key to classify/route upon.")
    branches: list[AgenticSwitchBranch] = Field(
        default_factory=list, description="List of classification cases and their targets."
    )


# --- Core Gold Standard Tools ---


class UpsertNode(BaseModel):
    id: str = Field(description="Unique node ID.")
    node_type: Literal[
        "LOGICAL_ASSIGNER",
        "AGENTIC_ASSIGNER",
        "RAG_RETRIEVER",
        "INTERRUPT",
        "LOGICAL_SWITCH",
        "AGENTIC_SWITCH",
    ] = Field(description="Type of the node.")
    config: (
        LogicalAssignerConfig
        | AgenticAssignerConfig
        | RagRetrieverConfig
        | InterruptConfig
        | LogicalSwitchConfig
        | AgenticSwitchConfig
    ) = Field(description="Node type-specific configuration object.")
    target: str | None = Field(
        default=None,
        description="Downstream target node ID (or 'end') for linear nodes. Leave null for switch nodes.",
    )


class UpsertSwitchBranch(BaseModel):
    node_id: str = Field(description="ID of the switch node to add or update the branch on.")
    label: str = Field(description="Branch label/case name.")
    target: str = Field(description="Downstream target node ID (or 'end').")
    condition: ConditionGroup | None = Field(
        default=None,
        description="Condition group for LOGICAL_SWITCH. Leave null for default branch or AGENTIC_SWITCH.",
    )


class RerouteEdge(BaseModel):
    source: str = Field(description="Source node ID (or 'start').")
    branch: str | None = Field(
        default=None,
        description="Branch label if source is a switch node. Leave null for linear nodes and 'start'.",
    )
    new_target: str | None = Field(
        default=None,
        description="New target node ID (or 'end'). Set to null to disconnect.",
    )


class DeleteEntity(BaseModel):
    kind: Literal["node", "variable", "switch_branch"] = Field(description="Kind of entity to delete.")
    id: str = Field(description="Node ID, variable key, or branch label to delete.")
    parent_id: str | None = Field(
        default=None,
        description="Parent switch node ID when kind='switch_branch'. Leave null for node/variable.",
    )


class RenameEntity(BaseModel):
    kind: Literal["node", "variable"] = Field(description="Kind of entity to rename.")
    old_name: str = Field(description="Current name/ID.")
    new_name: str = Field(description="New name/ID.")
