from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.modules.graphs.expressions.schemas import ComparisonFilter
from app.modules.graphs.operations import (
    AgenticOutputInput,
    AssignmentInput,
)


class UpsertVariable(BaseModel):
    key: str = Field(description="Variable key to create or update.")
    type: Literal["boolean", "bool", "string", "number", "float", "int", "integer"] = Field(
        description="Variable type."
    )
    default_value: Any | None = Field(
        default=None,
        description="Optional default value. Must be explicitly set to null/none if not present.",
    )
    description: str | None = Field(
        default=None,
        description="Optional variable description. Must be explicitly set to null/none if not present.",
    )


class DeleteVariable(BaseModel):
    key: str = Field(description="Key of the variable to delete.")


class RenameVariable(BaseModel):
    old_key: str = Field(description="Current key name.")
    new_key: str = Field(description="New key name.")


class UpsertLogicalAssigner(BaseModel):
    id: str = Field(description="Logical assigner node ID.")
    assignments: list[AssignmentInput] = Field(
        description="List of assignments to execute (each has target_var_key and expression)."
    )


class UpsertAgenticAssigner(BaseModel):
    id: str = Field(description="Agentic assigner node ID.")
    prompt: str = Field(description="Prompt template instruction.")
    agentic_inputs: list[str] = Field(
        default_factory=list,
        description="Variables passed to the agent. Pass [] if empty.",
    )
    agentic_outputs: list[AgenticOutputInput] = Field(
        default_factory=list,
        description="Output variables generated by the agent. Pass [] if empty.",
    )


class UpsertLogicalSwitch(BaseModel):
    id: str = Field(description="Logical switch node ID.")
    branches: dict[str, dict[str, ComparisonFilter] | None] = Field(
        description="Map of branch labels to conditional query expressions (use null for default/fallback branch)."
    )


class UpsertAgenticSwitch(BaseModel):
    id: str = Field(description="Agentic switch node ID.")
    agentic_input: str = Field(description="Input variable key to route upon.")
    branches: list[str] = Field(
        default_factory=list,
        description="List of branch labels/cases. Pass [] if empty.",
    )


class UpsertRagRetriever(BaseModel):
    id: str = Field(description="RAG retriever node ID.")
    query_var: str = Field(description="Variable containing the search query string.")
    context_output_var: str = Field(description="Variable to output the retrieved context string.")
    knowledge_base: str = Field(description="Target knowledge base identifier.")
    top_k: int = Field(default=3, description="Number of context records to retrieve.")


class UpsertInterrupt(BaseModel):
    id: str = Field(description="Interrupt node ID.")
    resume_var: str = Field(description="Variable to write resume value to.")
    payload_vars: list[str] = Field(
        default_factory=list,
        description="Variables to send in the interrupt payload. Pass [] if empty.",
    )


class DeleteNode(BaseModel):
    id: str = Field(description="Node ID to delete.")


class RenameNode(BaseModel):
    old_id: str = Field(description="Current node ID.")
    new_id: str = Field(description="New node ID.")


class Connect(BaseModel):
    source: str = Field(description="Source node ID (or 'start' for the graph entrypoint).")
    target: str = Field(description="Target node ID.")
    branch: str | None = Field(
        default=None,
        description="Branch label if source is a switch node (e.g. 'Yes', 'No', 'error'). Leave null for linear nodes and 'start'.",
    )


class Disconnect(BaseModel):
    source: str = Field(description="Source node ID (or 'start') to disconnect.")
    branch: str | None = Field(
        default=None,
        description="Branch label if source is a switch node. Leave null for linear nodes.",
    )
