from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.modules.graphs.operations import (
    AgenticOutputInput,
    AssignmentInput,
)


class UpsertVariable(BaseModel):
    key: str = Field(description="Variable key to create or update.")
    type: Literal["boolean", "bool", "string", "number", "float", "int", "integer"] = Field(
        description="Variable type."
    )
    default_value: Any | None = Field(
        description="Optional default value. Must be explicitly set to null/none if not present."
    )
    description: str | None = Field(
        description="Optional variable description. Must be explicitly set to null/none if not present."
    )


class DeleteVariable(BaseModel):
    key: str = Field(description="Key of the variable to delete.")


class RenameVariable(BaseModel):
    old_key: str = Field(description="Current key name.")
    new_key: str = Field(description="New key name.")


class UpsertLogicalAssigner(BaseModel):
    id: str = Field(description="Logical assigner node ID.")
    assignments: list[AssignmentInput] = Field(
        description="List of assignments to execute (each has target_var_key and expression)."
    )


class UpsertAgenticAssigner(BaseModel):
    id: str = Field(description="Agentic assigner node ID.")
    agentic_inputs: list[str] = Field(description="Variables passed to the agent. Explicitly pass [] if empty.")
    agentic_outputs: list[AgenticOutputInput] = Field(
        description="Output variables generated by the agent. Explicitly pass [] if empty."
    )
    prompt: str = Field(description="Prompt template instruction.")


class UpsertLogicalSwitch(BaseModel):
    id: str = Field(description="Logical switch node ID.")
    branches: dict[str, Any] = Field(description="Map of branch labels to conditional query expressions.")


class UpsertAgenticSwitch(BaseModel):
    id: str = Field(description="Agentic switch node ID.")
    agentic_input: str = Field(description="Input variable key to route upon.")
    branches: list[str] = Field(description="List of branch labels/cases. Explicitly pass [] if empty.")


class UpsertRagRetriever(BaseModel):
    id: str = Field(description="RAG retriever node ID.")
    query_var: str = Field(description="Variable containing the search query string.")
    context_output_var: str = Field(description="Variable to output the retrieved context string.")
    knowledge_base: str = Field(description="Target knowledge base identifier.")
    top_k: int = Field(description="Number of context records to retrieve.")


class UpsertInterrupt(BaseModel):
    id: str = Field(description="Interrupt node ID.")
    payload_vars: list[str] = Field(
        description="Variables to send in the interrupt payload. Explicitly pass [] if empty."
    )
    resume_var: str = Field(description="Variable to write resume value to.")


class DeleteNode(BaseModel):
    id: str = Field(description="Node ID to delete.")


class RenameNode(BaseModel):
    old_id: str = Field(description="Current node ID.")
    new_id: str = Field(description="New node ID.")


class SetStartTarget(BaseModel):
    target: str = Field(description="Target node ID of the start entrypoint node.")


class UpsertLinearEdge(BaseModel):
    source: str = Field(
        description="Source linear node ID (LOGICAL_ASSIGNER, AGENTIC_ASSIGNER, RAG_RETRIEVER, INTERRUPT)."
    )
    target: str = Field(description="Target node ID.")


class UpsertSwitchEdge(BaseModel):
    source: str = Field(description="Source switch node ID (LOGICAL_SWITCH, AGENTIC_SWITCH).")
    branch_label: str = Field(description="Switch branch label to route from.")
    target: str = Field(description="Target node ID.")


class DeleteLinearEdge(BaseModel):
    source: str = Field(description="Source linear node ID to disconnect.")


class DeleteSwitchEdge(BaseModel):
    source: str = Field(description="Source switch node ID to disconnect from.")
    branch_label: str = Field(description="Switch branch label to disconnect.")
