"""add_rag_document_chunks

Revision ID: a2ac71d0d169
Revises: b1365a74f595
Create Date: 2026-08-12 15:28:04.036183

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2ac71d0d169"
down_revision: str | Sequence[str] | None = "b1365a74f595"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("knowledge_base", sa.String(length=50), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=384), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_chunks_knowledge_base"), "document_chunks", ["knowledge_base"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_chunks_knowledge_base"), table_name="document_chunks")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
