from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class UpsertVariable(BaseModel):
    key: str = Field(description="Variable identifier name (alphanumeric and underscores).")
    type: Literal["string", "number", "boolean", "array", "object"] = Field(
        description="JSON data type of the state variable."
    )
    default_value: Any = Field(default=None, description="Initial default value for the variable.")
    description: str | None = Field(default=None, description="Optional docstring / description for the variable.")


class LogicalAssignment(BaseModel):
    target_var_key: str = Field(description="State variable to update.")
    expression: str = Field(
        description="Safe Python expression string to compute the new value (e.g. 'score + 10', 'user_answer', 'parsed_answer == correct_answer', 'min(15, score + 1)', 'random.choice(options)', '[]')."
    )


class LogicalAssignerConfig(BaseModel):
    assignments: list[LogicalAssignment] = Field(description="State assignments performed by this node.")


class LogicalBranch(BaseModel):
    label: str = Field(description="Branch label/case name.")
    target: str = Field(description="Downstream target node ID (or 'end').")
    condition: str | None = Field(
        default=None,
        description="Python boolean expression string (e.g. 'score < 15', 'is_correct == True', 'has_lifeline'). Leave null for the default/else branch.",
    )


class LogicalSwitchConfig(BaseModel):
    branches: list[LogicalBranch] = Field(description="Conditional routing branches.")


class AgenticAssignerConfig(BaseModel):
    prompt: str = Field(description="Instruction prompt for the LLM.")
    inputs: list[str] = Field(description="State variables interpolated into the prompt via {var_name}.")
    outputs: list[str] = Field(description="State variables generated by the LLM.")


class AgenticBranch(BaseModel):
    label: str = Field(description="Branch label/intent name.")
    target: str = Field(description="Downstream target node ID (or 'end').")


class AgenticSwitchConfig(BaseModel):
    agentic_input: str = Field(description="State variable containing user input to classify.")
    branches: list[AgenticBranch] = Field(description="Classification branches.")


class InterruptConfig(BaseModel):
    payload_vars: list[str] = Field(description="State variables exposed to the human.")
    resume_var: str = Field(description="State variable that will receive human input on resume.")


class RagRetrieverConfig(BaseModel):
    query_var: str = Field(description="State variable containing the search query.")
    context_output_var: str = Field(description="State variable to write retrieved context into.")
    knowledge_base: str = Field(default="trivia", description="Knowledge base name.")
    top_k: int = Field(default=3, description="Number of documents to retrieve.")


class UpsertNode(BaseModel):
    id: str = Field(description="Unique node ID, or 'start' to set graph entrypoint.")
    node_type: (
        Literal[
            "LOGICAL_ASSIGNER",
            "AGENTIC_ASSIGNER",
            "RAG_RETRIEVER",
            "INTERRUPT",
            "LOGICAL_SWITCH",
            "AGENTIC_SWITCH",
        ]
        | None
    ) = Field(
        default=None,
        description="Type of the node. Required when creating new nodes; optional when retargeting existing nodes.",
    )
    config: (
        LogicalAssignerConfig
        | AgenticAssignerConfig
        | RagRetrieverConfig
        | InterruptConfig
        | LogicalSwitchConfig
        | AgenticSwitchConfig
        | None
    ) = Field(
        default=None,
        description="Node type-specific configuration object. Optional when updating existing node target only.",
    )
    target: str | None = Field(
        default=None,
        description="Downstream target node ID (or 'end') for linear nodes and 'start'. Leave null for switch nodes.",
    )


class UpsertSwitchBranch(BaseModel):
    node_id: str = Field(description="ID of the switch node to add or update the branch on.")
    label: str = Field(description="Branch label/case name.")
    target: str = Field(description="Downstream target node ID (or 'end').")
    condition: str | None = Field(
        default=None,
        description="Python condition string for LOGICAL_SWITCH (e.g. 'score >= 15'). Leave null for default branch or AGENTIC_SWITCH.",
    )


class DeleteEntity(BaseModel):
    kind: Literal["node", "variable", "switch_branch"] = Field(description="Kind of entity to delete.")
    id: str = Field(description="Node ID, variable key, or branch label to delete.")
    parent_id: str | None = Field(
        default=None,
        description="Parent switch node ID when kind='switch_branch'. Leave null for node/variable.",
    )


class RenameEntity(BaseModel):
    kind: Literal["node", "variable"] = Field(description="Kind of entity to rename.")
    old_name: str = Field(description="Current name/ID.")
    new_name: str = Field(description="New name/ID.")


class ApplyGraphPlan(BaseModel):
    """Declarative atomic plan to mutate the graph in a single atomic turn."""

    variables: list[UpsertVariable] = Field(default_factory=list, description="State variables to create or update.")
    nodes: list[UpsertNode] = Field(default_factory=list, description="Nodes to create, update, or retarget.")
    switch_branches: list[UpsertSwitchBranch] = Field(
        default_factory=list, description="Surgical switch branches to add or update."
    )
    deletions: list[DeleteEntity] = Field(
        default_factory=list, description="Entities (nodes, variables, or branches) to delete."
    )
    renames: list[RenameEntity] = Field(default_factory=list, description="Entities (nodes or variables) to rename.")
