from __future__ import annotations

import json
from typing import Any, cast

from app.core.exceptions import ValidationError
from app.modules.copilot import planner_schemas
from app.modules.copilot.state import CopilotState


def convert_condition_group(group: dict[str, Any] | None) -> dict[str, Any] | None:
    """Converts a closed-schema ConditionGroup dictionary into internal ComparisonExpression AST."""
    if not group:
        return None
    conditions = group.get("conditions", [])
    if not conditions:
        return None

    converted: list[dict[str, Any]] = []
    for c in conditions:
        var = c["var"]
        op = c["op"]
        compare_var = c.get("compare_var")
        literal_val = c.get("literal_value")
        right_side = {"var": compare_var} if compare_var is not None else literal_val

        converted.append({var: {op: right_side}})

    if len(converted) == 1 and group.get("logic") != "NOT":
        return converted[0]

    logic = group.get("logic", "ALL")
    if logic == "ANY":
        return {"OR": converted}
    if logic == "NOT":
        not_inner: dict[str, Any] = converted[0] if len(converted) == 1 else {"AND": converted}
        return {"NOT": not_inner}
    return {"AND": converted}


def convert_assignment(asgn: dict[str, Any]) -> dict[str, Any]:
    """Converts a StrictAssignment dictionary into internal Assignment AST format."""
    target_var_key = asgn["target_var_key"]
    inner = asgn.get("assignment", {})
    if isinstance(inner, dict):
        if "var" in inner and len(inner) == 1:
            expr = {"var": inner["var"]}
        elif "value" in inner and len(inner) == 1:
            expr = inner["value"]
        elif "op" in inner and inner["op"] in {"increment", "decrement", "multiply", "divide"} and "amount" in inner:
            expr = {inner["op"]: inner["amount"]}
        else:
            expr = inner
    else:
        expr = inner
    return {"target_var_key": target_var_key, "expression": expr}


def translate_plan_to_operations(
    tool_calls: list[dict[str, Any]],
    initial_flow_data: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Deterministically parses and translates the planner's apply_graph_plan tool call into a validated GraphUpdateInput payload."""
    if not tool_calls:
        raise ValidationError("No tool calls generated by planner.")

    # Find the apply_graph_plan tool call
    plan_call = next((tc for tc in tool_calls if tc.get("name") == "apply_graph_plan"), None)
    if not plan_call:
        raise ValidationError(f"Expected tool call 'apply_graph_plan', found: {[tc.get('name') for tc in tool_calls]}")

    args_raw = plan_call.get("arguments", "{}")
    if isinstance(args_raw, str):
        try:
            args_dict = json.loads(args_raw)
        except Exception as e:
            raise ValidationError(f"Failed to parse arguments JSON for 'apply_graph_plan': {str(e)}")
    elif isinstance(args_raw, dict):
        args_dict = args_raw
    else:
        raise ValidationError("Invalid arguments format for 'apply_graph_plan'")

    try:
        plan = planner_schemas.ApplyGraphPlan.model_validate(args_dict)
    except Exception as e:
        raise ValidationError(f"Arguments validation failed for 'apply_graph_plan': {str(e)}")

    update_payload: dict[str, Any] = {
        "start_target": None,
        "variables": {"upsert": [], "delete": []},
        "nodes": {"upsert": [], "delete": []},
        "rename_variables": [],
        "rename_nodes": [],
    }

    initial_nodes = (initial_flow_data or {}).get("nodes", [])
    initial_node_map = {n.get("id"): n for n in initial_nodes if n.get("id")}

    def get_or_create_upsert(node_id: str) -> dict[str, Any]:
        for u in update_payload["nodes"]["upsert"]:
            if u["id"] == node_id:
                return cast(dict[str, Any], u)
        if node_id in initial_node_map:
            initial_node = initial_node_map[node_id]
            node_type = initial_node.get("node_type") or initial_node.get("node_class")
            node_update: dict[str, Any] = {"id": node_id, "node_type": node_type}
            if node_type in {"LOGICAL_SWITCH", "AGENTIC_SWITCH"}:
                branches = {}
                for br in initial_node.get("branches", []):
                    branch_id = br.get("id")
                    edge_target = None
                    for edge in (initial_flow_data or {}).get("edges", []):
                        if edge.get("source") == node_id and edge.get("source_handle") == branch_id:
                            edge_target = edge.get("target")
                            break
                    branches[br["label"]] = {
                        "expression": br.get("expression"),
                        "target": edge_target,
                    }
                node_update["branches"] = branches
                if node_type == "AGENTIC_SWITCH":
                    node_update["agentic_input"] = initial_node.get("agentic_input")
            else:
                edge_target = None
                for edge in (initial_flow_data or {}).get("edges", []):
                    if edge.get("source") == node_id and edge.get("source_handle") is None:
                        edge_target = edge.get("target")
                        break
                node_update["target"] = edge_target

                if node_type == "LOGICAL_ASSIGNER":
                    assignments = []
                    for asgn in initial_node.get("assignments", []):
                        assignments.append(
                            {
                                "target_var_key": asgn.get("target_var_key"),
                                "expression": asgn.get("expression"),
                            }
                        )
                    node_update["assignments"] = assignments
                elif node_type == "AGENTIC_ASSIGNER":
                    node_update["agentic_inputs"] = initial_node.get("agentic_inputs", [])
                    node_update["agentic_outputs"] = initial_node.get("agentic_outputs", [])
                    node_update["prompt"] = initial_node.get("prompt", "")
                elif node_type == "RAG_RETRIEVER":
                    node_update["query_var"] = initial_node.get("query_var")
                    node_update["context_output_var"] = initial_node.get("context_output_var")
                    node_update["knowledge_base"] = initial_node.get("knowledge_base")
                    node_update["top_k"] = initial_node.get("top_k")
                elif node_type == "INTERRUPT":
                    node_update["payload_vars"] = initial_node.get("payload_vars", [])
                    node_update["resume_var"] = initial_node.get("resume_var")

            update_payload["nodes"]["upsert"].append(node_update)
            return node_update
        raise ValidationError(f"Cannot route edge from unknown node '{node_id}'.")

    # 1. Variables
    for var in plan.variables:
        update_payload["variables"]["upsert"].append(var.model_dump(mode="json"))

    # 2. Renames
    for rn in plan.renames:
        if rn.kind == "node":
            update_payload["rename_nodes"].append({"old_key": rn.old_name, "new_key": rn.new_name})
        elif rn.kind == "variable":
            update_payload["rename_variables"].append({"old_key": rn.old_name, "new_key": rn.new_name})

    # 3. Deletions
    for dl in plan.deletions:
        if dl.kind == "node":
            update_payload["nodes"]["delete"].append(dl.id)
        elif dl.kind == "variable":
            update_payload["variables"]["delete"].append(dl.id)
        elif dl.kind == "switch_branch":
            if not dl.parent_id:
                raise ValidationError("parent_id is required when deleting a switch_branch")
            node = get_or_create_upsert(dl.parent_id)
            if "branches" in node and dl.id in node["branches"]:
                node["branches"].pop(dl.id, None)

    # 4. Nodes
    for n in plan.nodes:
        node_id = n.id
        node_type = n.node_type
        config = n.config
        target = n.target

        if node_id.lower() == "start":
            update_payload["start_target"] = target
        elif config is None:
            node = get_or_create_upsert(node_id)
            if target is not None:
                node["target"] = target
        else:
            config_dict = config.model_dump(mode="json")
            node_update: dict[str, Any]
            if node_type == "LOGICAL_ASSIGNER":
                assignments = [convert_assignment(a) for a in config_dict.get("assignments", [])]
                node_update = {
                    "id": node_id,
                    "node_type": node_type,
                    "assignments": assignments,
                }
                if target is not None:
                    node_update["target"] = target
                update_payload["nodes"]["upsert"].append(node_update)

            elif node_type == "AGENTIC_ASSIGNER":
                node_update = {
                    "id": node_id,
                    "node_type": node_type,
                    "prompt": config_dict.get("prompt"),
                    "agentic_inputs": config_dict.get("agentic_inputs", []),
                    "agentic_outputs": config_dict.get("agentic_outputs", []),
                }
                if target is not None:
                    node_update["target"] = target
                update_payload["nodes"]["upsert"].append(node_update)

            elif node_type == "RAG_RETRIEVER":
                node_update = {
                    "id": node_id,
                    "node_type": node_type,
                    "query_var": config_dict.get("query_var"),
                    "context_output_var": config_dict.get("context_output_var"),
                    "knowledge_base": config_dict.get("knowledge_base"),
                    "top_k": config_dict.get("top_k", 3),
                }
                if target is not None:
                    node_update["target"] = target
                update_payload["nodes"]["upsert"].append(node_update)

            elif node_type == "INTERRUPT":
                node_update = {
                    "id": node_id,
                    "node_type": node_type,
                    "resume_var": config_dict.get("resume_var"),
                    "payload_vars": config_dict.get("payload_vars", []),
                }
                if target is not None:
                    node_update["target"] = target
                update_payload["nodes"]["upsert"].append(node_update)

            elif node_type == "LOGICAL_SWITCH":
                branches = {}
                for b in config_dict.get("branches", []):
                    expr_ast = convert_condition_group(b.get("condition"))
                    branches[b["label"]] = {"expression": expr_ast, "target": b.get("target")}
                node_update = {"id": node_id, "node_type": node_type, "branches": branches}
                update_payload["nodes"]["upsert"].append(node_update)

            elif node_type == "AGENTIC_SWITCH":
                branches = {}
                for b in config_dict.get("branches", []):
                    branches[b["label"]] = {"expression": None, "target": b.get("target")}
                node_update = {
                    "id": node_id,
                    "node_type": node_type,
                    "agentic_input": config_dict.get("agentic_input"),
                    "branches": branches,
                }
                update_payload["nodes"]["upsert"].append(node_update)

    # 5. Surgical Switch Branches
    for sb in plan.switch_branches:
        node = get_or_create_upsert(sb.node_id)
        if "branches" not in node or node["branches"] is None:
            node["branches"] = {}
        expr_ast = convert_condition_group(sb.condition.model_dump(mode="json") if sb.condition else None)
        node["branches"][sb.label] = {"expression": expr_ast, "target": sb.target}

    return update_payload


def translate_plan_node(state: CopilotState) -> dict[str, Any]:
    """LangGraph node wrapper: translates plan tool call to operations."""
    tool_calls = state.get("tool_calls") or []
    initial_flow_data = state.get("initial_flow_data")

    try:
        operations = translate_plan_to_operations(tool_calls, initial_flow_data)
        return {"operations": operations, "validation_error": None}
    except Exception as e:
        return {"operations": None, "validation_error": str(e)}
