from __future__ import annotations

import logging
import os
from typing import Any, Literal, cast

from google import genai
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph

from app.core.exceptions import ValidationError
from app.modules.copilot.agents.planner import generate_plan
from app.modules.copilot.logger import log_validation_error
from app.modules.copilot.models import CopilotState
from app.modules.graphs.operations import GraphUpdateInput, apply_graph_update
from app.modules.graphs.schemas import GraphFlowData

logger = logging.getLogger(__name__)


async def planner_node(state: CopilotState) -> dict[str, Any]:
    """Invokes the Planner LLM to generate the checklist of agent tasks."""
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise ValidationError("GEMINI_API_KEY environment variable is not set.")

    client = genai.Client(api_key=api_key)

    messages = [
        {
            "role": "user",
            "content": f"## Current Graph State:\n{state['serialized_state']}\n\n## User Request:\n{state['user_prompt']}",
        },
    ]

    plan = await generate_plan(client, state["trace_id"], state.get("graph_id", ""), messages)
    checklist = {"tool_calls": plan}

    return {
        "agent_checklist": checklist,
        "operations": None,
        "plan": [],
    }


def translate_plan_node(state: CopilotState) -> dict[str, Any]:
    """Deterministically validates planner operations and maps them straight to the update object."""
    import json

    from pydantic import BaseModel

    from app.modules.copilot.agents import planner_schemas

    checklist = state.get("agent_checklist") or {}
    tool_calls = checklist.get("tool_calls") or []

    # Construct standard GraphUpdateInput payload
    update_payload: dict[str, Any] = {
        "start_target": None,
        "variables": {"upsert": [], "delete": []},
        "nodes": {"upsert": [], "delete": []},
        "rename_variables": [],
        "rename_nodes": [],
    }

    # Map name of tool call to its corresponding validation schema
    schema_map: dict[str, type[BaseModel]] = {
        "upsert_variable": planner_schemas.UpsertVariable,
        "delete_variable": planner_schemas.DeleteVariable,
        "rename_variable": planner_schemas.RenameVariable,
        "upsert_logical_assigner": planner_schemas.UpsertLogicalAssigner,
        "upsert_agentic_assigner": planner_schemas.UpsertAgenticAssigner,
        "upsert_logical_switch": planner_schemas.UpsertLogicalSwitch,
        "upsert_agentic_switch": planner_schemas.UpsertAgenticSwitch,
        "upsert_rag_retriever": planner_schemas.UpsertRagRetriever,
        "upsert_interrupt": planner_schemas.UpsertInterrupt,
        "delete_node": planner_schemas.DeleteNode,
        "rename_node": planner_schemas.RenameNode,
        "connect": planner_schemas.Connect,
        "disconnect": planner_schemas.Disconnect,
    }

    upsert_calls = []
    routing_calls = []
    for tc in tool_calls:
        if tc.get("name") in {"connect", "disconnect"}:
            routing_calls.append(tc)
        else:
            upsert_calls.append(tc)

    # First pass: Handle node definitions and variable updates
    for tc in upsert_calls:
        name = tc.get("name")
        args_str = tc.get("arguments", "{}")
        try:
            args_dict = json.loads(args_str)
        except Exception as e:
            raise ValidationError(f"Failed to parse arguments for tool '{name}': {str(e)}")

        schema = schema_map.get(name)
        if not schema:
            raise ValidationError(f"Unknown tool call generated by planner: '{name}'")

        # Validate arguments using the specific tool Pydantic schema
        try:
            validated = schema.model_validate(args_dict)
        except Exception as e:
            raise ValidationError(f"Arguments validation failed for tool '{name}': {str(e)}")

        args = validated.model_dump(mode="json")

        if name == "upsert_variable":
            update_payload["variables"]["upsert"].append(args)
        elif name == "delete_variable":
            update_payload["variables"]["delete"].append(args["key"])
        elif name == "rename_variable":
            update_payload["rename_variables"].append({"old_key": args["old_key"], "new_key": args["new_key"]})
        elif name == "delete_node":
            update_payload["nodes"]["delete"].append(args["id"])
        elif name == "rename_node":
            update_payload["rename_nodes"].append({"old_key": args["old_id"], "new_key": args["new_id"]})
        elif name == "upsert_logical_switch":
            branches = {}
            for label, expr in args.get("branches", {}).items():
                branches[label] = {"expression": expr, "target": None}
            update_payload["nodes"]["upsert"].append(
                {"id": args["id"], "node_type": "LOGICAL_SWITCH", "branches": branches}
            )
        elif name == "upsert_agentic_switch":
            branches = {}
            for label in args.get("branches", []):
                branches[label] = {"target": None}
            update_payload["nodes"]["upsert"].append(
                {
                    "id": args["id"],
                    "node_type": "AGENTIC_SWITCH",
                    "agentic_input": args["agentic_input"],
                    "branches": branches,
                }
            )
        elif name.startswith("upsert_"):
            # Node upserts (logical_assigner, agentic_assigner, etc.)
            node_type = name.replace("upsert_", "").upper()
            node_update = {"id": args["id"], "node_type": node_type}

            # Map valid keys over to generic NodeUpsertInput shape
            for field in [
                "target",
                "assignments",
                "agentic_inputs",
                "agentic_outputs",
                "prompt",
                "branches",
                "agentic_input",
                "query_var",
                "context_output_var",
                "knowledge_base",
                "top_k",
                "payload_vars",
                "resume_var",
            ]:
                if field in args and args[field] is not None:
                    node_update[field] = args[field]
            update_payload["nodes"]["upsert"].append(node_update)

    # Second pass: Process node routing edges via connect / disconnect tools
    initial_nodes = state.get("initial_flow_data", {}).get("nodes", [])
    initial_node_map = {n.get("id"): n for n in initial_nodes if n.get("id")}

    def get_or_create_upsert(node_id: str) -> dict[str, Any]:
        for u in update_payload["nodes"]["upsert"]:
            if u["id"] == node_id:
                return cast(dict[str, Any], u)
        if node_id in initial_node_map:
            initial_node = initial_node_map[node_id]
            node_type = initial_node.get("node_type") or initial_node.get("node_class")
            node_update: dict[str, Any] = {"id": node_id, "node_type": node_type}
            if node_type in {"LOGICAL_SWITCH", "AGENTIC_SWITCH"}:
                branches = {}
                for br in initial_node.get("branches", []):
                    branch_id = br.get("id")
                    edge_target = None
                    for edge in state.get("initial_flow_data", {}).get("edges", []):
                        if edge.get("source") == node_id and edge.get("source_handle") == branch_id:
                            edge_target = edge.get("target")
                            break
                    expr_id = br.get("expr_id")
                    expr_val = None
                    if expr_id:
                        expr_record = state.get("initial_flow_data", {}).get("expressions", {}).get(expr_id)
                        if expr_record:
                            expr_val = expr_record.get("expr")
                    branches[br["label"]] = {
                        "expression": expr_val,
                        "target": edge_target,
                    }
                node_update["branches"] = branches
            else:
                edge_target = None
                for edge in state.get("initial_flow_data", {}).get("edges", []):
                    if edge.get("source") == node_id and edge.get("source_handle") is None:
                        edge_target = edge.get("target")
                        break
                node_update["target"] = edge_target

                if node_type == "LOGICAL_ASSIGNER":
                    assignments = []
                    for asgn in initial_node.get("assignments", []):
                        expr_id = asgn.get("expr_id")
                        expr_val = None
                        if expr_id:
                            expr_record = state.get("initial_flow_data", {}).get("expressions", {}).get(expr_id)
                            if expr_record:
                                expr_val = expr_record.get("expr")
                        assignments.append(
                            {
                                "target_var_key": asgn.get("target_var_key"),
                                "expression": expr_val,
                            }
                        )
                    node_update["assignments"] = assignments
                elif node_type == "AGENTIC_ASSIGNER":
                    node_update["agentic_inputs"] = initial_node.get("agentic_inputs", [])
                    node_update["agentic_outputs"] = initial_node.get("agentic_outputs", [])
                    node_update["prompt"] = initial_node.get("prompt", "")
                elif node_type == "RAG_RETRIEVER":
                    node_update["query_var"] = initial_node.get("query_var")
                    node_update["context_output_var"] = initial_node.get("context_output_var")
                    node_update["knowledge_base"] = initial_node.get("knowledge_base")
                    node_update["top_k"] = initial_node.get("top_k")
                elif node_type == "INTERRUPT":
                    node_update["payload_vars"] = initial_node.get("payload_vars", [])
                    node_update["resume_var"] = initial_node.get("resume_var")

            update_payload["nodes"]["upsert"].append(node_update)
            return node_update
        raise ValidationError(f"Cannot route edge from unknown node '{node_id}'.")

    for tc in routing_calls:
        name = tc.get("name")
        args_str = tc.get("arguments", "{}")
        try:
            args_dict = json.loads(args_str)
        except Exception as e:
            raise ValidationError(f"Failed to parse arguments for tool '{name}': {str(e)}")

        schema = schema_map.get(name)
        if not schema:
            raise ValidationError(f"Unknown tool call generated by planner: '{name}'")

        try:
            validated = schema.model_validate(args_dict)
        except Exception as e:
            raise ValidationError(f"Arguments validation failed for tool '{name}': {str(e)}")

        args = validated.model_dump(mode="json")
        source_id = args["source"]
        branch_label = args.get("branch")

        if name == "connect":
            target_id = args["target"]
            if source_id.lower() == "start":
                update_payload["start_target"] = target_id
            else:
                node = get_or_create_upsert(source_id)
                if node["node_type"] in {"LOGICAL_SWITCH", "AGENTIC_SWITCH"}:
                    if not branch_label:
                        raise ValidationError(
                            f"Cannot connect switch node '{source_id}' without specifying a branch label."
                        )
                    if "branches" not in node:
                        node["branches"] = {}
                    if branch_label not in node["branches"]:
                        node["branches"][branch_label] = {}
                    node["branches"][branch_label]["target"] = target_id
                else:
                    if branch_label:
                        raise ValidationError(f"Cannot specify branch '{branch_label}' for linear node '{source_id}'.")
                    node["target"] = target_id

        elif name == "disconnect":
            if source_id.lower() == "start":
                update_payload["start_target"] = None
            else:
                node = get_or_create_upsert(source_id)
                if node["node_type"] in {"LOGICAL_SWITCH", "AGENTIC_SWITCH"}:
                    if branch_label:
                        if "branches" not in node:
                            node["branches"] = {}
                        if branch_label not in node["branches"]:
                            node["branches"][branch_label] = {}
                        node["branches"][branch_label]["target"] = ""
                    else:
                        if "branches" in node:
                            for br in node["branches"].values():
                                if isinstance(br, dict):
                                    br["target"] = ""
                else:
                    node["target"] = ""

    validate_node_connectivity(update_payload, state.get("initial_flow_data"))

    result: dict[str, Any] = {"operations": update_payload}
    return result


def validate_node_connectivity(update_payload: dict[str, Any], initial_flow_data: dict[str, Any] | None) -> None:
    if not initial_flow_data:
        return

    initial_nodes = initial_flow_data.get("nodes", [])
    initial_node_ids = {n.get("id") for n in initial_nodes if n.get("id")}

    # Track renames
    renamed_ids = {}
    for rn in update_payload.get("rename_nodes", []):
        renamed_ids[rn["new_key"]] = rn["old_key"]

    # All upserted node IDs
    upserted_nodes = update_payload.get("nodes", {}).get("upsert", [])
    upserted_ids = {n["id"] for n in upserted_nodes}

    # Collect targeted IDs
    targeted_ids = set()
    if update_payload.get("start_target"):
        targeted_ids.add(update_payload["start_target"])

    for n in upserted_nodes:
        # Linear target
        if n.get("target"):
            targeted_ids.add(n["target"])
        # Branches targets
        branches = n.get("branches") or {}
        for br in branches.values():
            if br.get("target"):
                targeted_ids.add(br["target"])

    # Find brand new nodes
    new_nodes = set()
    for nid in upserted_ids:
        if nid not in initial_node_ids and nid not in renamed_ids:
            new_nodes.add(nid)

    for nid in new_nodes:
        if nid not in targeted_ids:
            raise ValidationError(
                f"Orphan node detected: The new node '{nid}' is not targeted by any transition. "
                "Ensure that a preceding node's target/branches routes to it."
            )


def aggregation_node(state: CopilotState) -> dict[str, Any]:
    """Aggregates the transaction update into a list of human-readable plan steps for the UI."""
    state_ops = state.get("operations") or {}
    try:
        update = GraphUpdateInput.model_validate(state_ops)
    except Exception as e:
        raise ValidationError(f"Agents generated invalid updates: {str(e)}")

    plan_steps = []
    if update.start_target:
        plan_steps.append(
            {
                "action": "set_start_target",
                "description": f"Set starting node to '{update.start_target}'",
                "details": {},
            }
        )
    if update.rename_variables:
        for ru in update.rename_variables:
            plan_steps.append(
                {
                    "action": "rename_variable",
                    "description": f"Rename variable '{ru.old_key}' to '{ru.new_key}'",
                    "details": {},
                }
            )
    if update.rename_nodes:
        for rn in update.rename_nodes:
            plan_steps.append(
                {"action": "rename_node", "description": f"Rename node '{rn.old_key}' to '{rn.new_key}'", "details": {}}
            )
    if update.variables:
        if update.variables.delete:
            for d in update.variables.delete:
                plan_steps.append({"action": "delete_variable", "description": f"Delete variable '{d}'", "details": {}})
        if update.variables.upsert:
            for u in update.variables.upsert:
                plan_steps.append(
                    {
                        "action": "upsert_variable",
                        "description": f"Upsert variable '{u.key}' (type: {u.type})",
                        "details": u.model_dump(),
                    }
                )
    if update.nodes:
        if update.nodes.delete:
            for dn in update.nodes.delete:
                plan_steps.append({"action": "delete_node", "description": f"Delete node '{dn}'", "details": {}})
        if update.nodes.upsert:
            for un in update.nodes.upsert:
                plan_steps.append(
                    {
                        "action": "upsert_node",
                        "description": f"Upsert node '{un.id}' (type: {un.node_type})",
                        "details": un.model_dump(),
                    }
                )

    return {"plan": plan_steps}


def wait_for_plan_node(state: CopilotState) -> dict[str, Any]:
    """Automatically approves the plan to continue workflow execution."""
    return {"plan_approved": True}


def validation_node(state: CopilotState) -> dict[str, Any]:
    """Validates generated operations by dry-running them against the backend mutations engine."""
    if not state.get("plan_approved") or not state.get("operations"):
        return {}

    try:
        flow_data = GraphFlowData.model_validate(state["initial_flow_data"])
        state_ops = state.get("operations") or {}
        update = GraphUpdateInput.model_validate(state_ops)

        # Dry-run patch application
        apply_graph_update(flow_data, update)
        return {"validation_error": None}
    except Exception as e:
        logger.warning("Agent operation dry-run failed: %s", str(e))
        log_validation_error(state["trace_id"], state.get("graph_id"), str(e))
        return {"validation_error": str(e)}


def wait_for_apply_node(state: CopilotState) -> dict[str, Any]:
    """Automatically approves applying the patch if validation succeeded."""
    has_error = bool(state.get("validation_error"))
    return {"apply_approved": not has_error}


def apply_node(state: CopilotState) -> dict[str, Any]:
    """Marks the state as applied so the service can persist changes."""
    if not state.get("apply_approved") or state.get("validation_error"):
        return {"applied": False}
    return {"applied": True}


# --- Graph Routing Logic ---


def route_after_plan(state: CopilotState) -> Literal["validation_node", "__end__"]:
    if state.get("plan_approved"):
        return "validation_node"
    return "__end__"


def route_after_apply(state: CopilotState) -> Literal["apply_node", "__end__"]:
    if state.get("apply_approved") and not state.get("validation_error"):
        return "apply_node"
    return "__end__"


# --- Build StateGraph ---

workflow = StateGraph(CopilotState)

workflow.add_node("planner_node", planner_node)
workflow.add_node("translate_plan_node", translate_plan_node)
workflow.add_node("aggregation_node", aggregation_node)
workflow.add_node("wait_for_plan_node", wait_for_plan_node)
workflow.add_node("validation_node", validation_node)
workflow.add_node("wait_for_apply_node", wait_for_apply_node)
workflow.add_node("apply_node", apply_node)

workflow.add_edge(START, "planner_node")
workflow.add_edge("planner_node", "translate_plan_node")
workflow.add_edge("translate_plan_node", "aggregation_node")
workflow.add_edge("aggregation_node", "wait_for_plan_node")
workflow.add_conditional_edges("wait_for_plan_node", route_after_plan)
workflow.add_edge("validation_node", "wait_for_apply_node")
workflow.add_conditional_edges("wait_for_apply_node", route_after_apply)
workflow.add_edge("apply_node", END)

# In-memory saver to persist threads across HTTP cycles
memory_saver = MemorySaver()
copilot_graph = workflow.compile(checkpointer=memory_saver)
